FROM accenture/adop-nginx:0.2.0

MAINTAINER john bryan sazon

COPY configuration /resources/configuration
COPY release_note /resources/release_note
COPY entrypoint.sh /resources/scripts/entrypoint.sh

